export const zodiac = [
  { name: 'aquarius',
    dates: 'Jan 19 - Feb 18',
  },
  { name: 'pisces',
    dates: 'Feb 18 - Mar 20',
  },
  { name: 'aries',
    dates: 'Mar 20 - Apr 19',
  },
  { name: 'taurus',
    dates: 'Apr 19 - May 20',
  },
  { name: 'gemini',
    dates: 'May 20 - Jun 21',
  },
  { name: 'cancer',
    dates: 'Jun 21 - Jul 22',
  },
  { name: 'leo',
    dates: 'Jul 22 - Aug 22',
  },
  { name: 'virgo',
    dates: 'Aug 22 - Sept 22',
  },
  { name: 'libra',
    dates: 'Sept 22 - Oct 23',
  },
  { name: 'scorpio',
    dates: 'Oct 23 - Nov 22',
  },
  { name: 'sagittarius',
    dates: 'Nov 22 - Dec 21',
  },
  { name: 'capricorn',
    dates: 'Dec 21 - Jan 19',
  },
];